version: '3.9'

services:
  app:
    build: .
    container_name: proprli_app
    volumes:
      - .:/var/www/html   # optional: sync local folder with container
    depends_on:
      - db
    networks:
      - laravel
    ports:
      - "9000:9000"   # php-fpm port
    tty: true

  db:
    image: postgres:15
    container_name: proprli_db
    environment:
      POSTGRES_DB: proprli
      POSTGRES_USER: proprli
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: proprli_nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel: